name: Build
on:
  push:
    branches: [ main, dev ]

jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from Gitea Actions!"

  checkout:
    runs-on: self-hosted
    container:
      image: node:20
    steps:
      - run: echo "on tiger hosted"

      - name: Checkout code
        uses: actions/checkout@v3

  build-image:
    runs-on: self-hosted
      - run: pwd
      - run: ls -la
      - run: docker version