name: Build
on:
  push:
    branches: [ main, dev ]

jobs:
  code-scan:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sonar version
        run: sonar-scanner --version

      - name: Run SonarQube Scanner 
        run: |
          sonar-scanner \
            -Dsonar.projectKey=pet-store \
            -Dsonar.projectName="pet-store" \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9099 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      
      - name: select osv-scanner version
        run: OSV_VERSION="latest"

      - name: scan app dependency # required the golang installation on the act_runner to generate the go.sum file
        run: osv-scanner --lockfile=go.sum

  build-and-push-image:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: login docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}"  | docker login 192.168.49.2:31269 -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Generate version tag
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: build image
        run: docker build -t 192.168.49.2:31269/pet-store:${{ env.VERSION }} .

      - name: scan image
        run: trivy image 192.168.49.2:31269/pet-store:${{ env.VERSION }}

      - name: push image
        run: docker push 192.168.49.2:31269/pet-store:${{ env.VERSION }}

    env:
      VERSION: ${{ env.VERSION }}